"""Recover simultaneous right symmetrisers from a public matrix tensor.

For ``G[i] = A.T @ H[i] @ B`` with Hankel ``H[i]`` and invertible ``A, B``,
every right symmetriser satisfies ``G[i] @ C`` symmetric.  When the span of the
``H[i]`` has dimension greater than ``n``, the solution space is exactly the
line generated by ``inverse(B) @ A``; this module solves and checks that public
linear system.  It does not assume that an arbitrary input has Hankel origin.

Arithmetic is over the prime field with modulus ``q``; the linear algebra is the
package's finite-field backend, without Sage.
"""
from __future__ import annotations

from .finite_field import kernel, np, rank


def _matmul_mod(left: np.ndarray, right: np.ndarray, q: int) -> np.ndarray:
    """Use int64 when its accumulation is safe, otherwise exact integers."""
    inner = left.shape[-1]
    if inner * (q - 1) ** 2 <= np.iinfo(np.int64).max:
        return (left @ right) % q
    return np.asarray((left.astype(object) @ right.astype(object)) % q, dtype=np.int64)


def _constraint_matrix(g: np.ndarray, q: int) -> np.ndarray:
    """Rows encode (G_i C)[a,b] - (G_i C)[b,a] for row-major C."""
    m, n, _ = g.shape
    upper_a, upper_b = np.triu_indices(n, k=1)
    pair_count = len(upper_a)
    constraints = np.zeros((m * pair_count, n * n), dtype=np.int64)
    if pair_count == 0:
        return constraints
    rows = np.arange(pair_count)
    for i in range(m):
        block = constraints[i * pair_count:(i + 1) * pair_count]
        for k in range(n):
            block[rows, k * n + upper_b] = g[i, upper_a, k]
            block[rows, k * n + upper_a] = (-g[i, upper_b, k]) % q
    return constraints


def recover_symmetrizer(G, q):
    """Return the symmetriser space of the tensor and its exact certificates.

    ``basis`` holds a complete independent basis of the solution space,
    ``rank`` is the rank of the symmetry constraint matrix and ``nullity`` its
    dimension.  When ``nullity == 1``, ``generator`` is the unique basis matrix,
    normalized so that its first nonzero row-major entry is one, and
    ``symmetric_matrices`` is ``G @ generator``.  Otherwise both are ``None``:
    the function does not select an arbitrary element of a higher-dimensional
    solution space.

    Raises ``ValueError``/``TypeError`` for an invalid shape, dtype or modulus,
    and ``ArithmeticError`` if a kernel basis fails an exact public certificate.
    """
    if isinstance(q, (bool, np.bool_)) or not isinstance(q, (int, np.integer)):
        raise TypeError("q must be an integer prime modulus")
    q = int(q)
    if not 2 <= q <= 65519:
        raise ValueError("the finite-field backend requires 2 <= q <= 65519")
    g = np.asarray(G)
    if g.ndim != 3 or g.shape[0] < 1 or g.shape[1] < 1 or g.shape[1] != g.shape[2]:
        raise ValueError("G must have shape (m,n,n), with m,n >= 1")
    if g.dtype.kind not in "iu":
        raise TypeError("G must contain integer field representatives")
    modulus = np.uint64(q) if g.dtype.kind == "u" else q
    g = np.ascontiguousarray(g % modulus, dtype=np.int64)
    m, n, _ = g.shape

    constraints = _constraint_matrix(g, q)
    # Avoid requiring the backend to special-case a matrix with zero rows.
    if constraints.shape[0] == 0:
        flat_basis = np.eye(n * n, dtype=np.int64)
    else:
        flat_basis = np.asarray(kernel(constraints, q), dtype=np.int64)
        if flat_basis.ndim != 2 or flat_basis.shape[1] != n * n:
            raise ArithmeticError("finite-field backend returned an invalid kernel shape")
        flat_basis = np.ascontiguousarray(flat_basis % q)
    nullity = len(flat_basis)
    if nullity > n * n:
        raise ArithmeticError("finite-field kernel dimension exceeds its ambient space")

    basis_independent = nullity == 0 or rank(flat_basis, q) == nullity
    basis = flat_basis.reshape(nullity, n, n)
    basis_symmetry = True
    for c in basis:
        product = _matmul_mod(g, c, q)
        if not np.array_equal(product, product.swapaxes(-1, -2)):
            basis_symmetry = False
            break
    if not basis_independent or not basis_symmetry:
        raise ArithmeticError("finite-field kernel failed the public symmetry certificate")

    generator = symmetric_matrices = None
    generator_symmetry = generator_rank = generator_invertible = None
    if nullity == 1:
        flat = flat_basis[0]
        leading = int(flat[np.flatnonzero(flat)[0]])
        scale = pow(leading, -1, q)
        # Python integers also keep normalization exact for large moduli.
        normalized = np.fromiter((int(value) * scale % q for value in flat),
                                 dtype=np.int64, count=n * n)
        basis = normalized.reshape(1, n, n)
        generator = basis[0].copy()
        symmetric_matrices = _matmul_mod(g, generator, q)
        generator_symmetry = bool(
            np.array_equal(symmetric_matrices, symmetric_matrices.swapaxes(-1, -2)))
        generator_rank = int(rank(generator, q))
        generator_invertible = generator_rank == n
        if not generator_symmetry:
            raise ArithmeticError("normalized generator failed the public symmetry certificate")

    return {
        "shape": (m, n, n),
        "basis": basis,
        "generator": generator,
        "symmetric_matrices": symmetric_matrices,
        # A complete kernel basis determines the rank by rank-nullity, so no
        # second elimination on the (potentially large) constraint matrix.
        "rank": n * n - nullity,
        "nullity": nullity,
        "checks": {
            "basis_independent": bool(basis_independent),
            "basis_exact_symmetry": bool(basis_symmetry),
            "generator_exact_symmetry": generator_symmetry,
            "generator_rank": generator_rank,
            "generator_invertible": generator_invertible,
        },
    }


__all__ = ["recover_symmetrizer"]
